[2025-06-13T14:09:24.019-0400] {processor.py:153} INFO - Started process (PID=96509) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:09:24.021-0400] {processor.py:743} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:09:24.021-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:09:24.021-0400] {dagbag.py:538} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:09:24.036-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:09:24.035-0400] {dagbag.py:343} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/drift-retrainer/venv311/lib/python3.11/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:09:24.037-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:09:24.859-0400] {processor.py:175} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 0.840 seconds
[2025-06-13T14:10:56.384-0400] {processor.py:153} INFO - Started process (PID=97203) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:10:56.386-0400] {processor.py:743} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:10:56.387-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:10:56.387-0400] {dagbag.py:538} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:10:56.400-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:10:56.399-0400] {dagbag.py:343} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/drift-retrainer/venv311/lib/python3.11/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:10:56.400-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:10:56.880-0400] {processor.py:175} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 0.496 seconds
[2025-06-13T14:11:55.086-0400] {processor.py:153} INFO - Started process (PID=97487) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:11:55.088-0400] {processor.py:743} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:11:55.088-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:11:55.088-0400] {dagbag.py:538} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:11:55.101-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:11:55.100-0400] {dagbag.py:343} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/drift-retrainer/venv311/lib/python3.11/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:11:55.101-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:11:55.596-0400] {processor.py:175} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 0.511 seconds
[2025-06-13T14:12:53.072-0400] {processor.py:153} INFO - Started process (PID=97748) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:12:53.074-0400] {processor.py:743} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:12:53.075-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:12:53.075-0400] {dagbag.py:538} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:12:53.086-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:12:53.086-0400] {dagbag.py:343} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/drift-retrainer/venv311/lib/python3.11/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:12:53.086-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:12:53.556-0400] {processor.py:175} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 0.484 seconds
[2025-06-13T14:13:48.270-0400] {processor.py:153} INFO - Started process (PID=97943) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:13:48.279-0400] {processor.py:743} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:13:48.279-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:13:48.279-0400] {dagbag.py:538} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:13:48.297-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:13:48.296-0400] {dagbag.py:343} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/drift-retrainer/venv311/lib/python3.11/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:13:48.297-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:13:48.741-0400] {processor.py:175} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 0.471 seconds
[2025-06-13T14:14:41.158-0400] {processor.py:153} INFO - Started process (PID=800) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:14:41.160-0400] {processor.py:743} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:14:41.161-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:14:41.160-0400] {dagbag.py:538} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:14:41.177-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:14:41.176-0400] {dagbag.py:343} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/drift-retrainer/venv311/lib/python3.11/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:14:41.177-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:14:41.670-0400] {processor.py:175} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 0.512 seconds
[2025-06-13T14:15:40.056-0400] {processor.py:153} INFO - Started process (PID=2945) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:15:40.058-0400] {processor.py:743} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:15:40.059-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:15:40.059-0400] {dagbag.py:538} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:15:40.072-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:15:40.071-0400] {dagbag.py:343} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/drift-retrainer/venv311/lib/python3.11/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:15:40.072-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:15:40.555-0400] {processor.py:175} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 0.499 seconds
[2025-06-13T14:16:38.573-0400] {processor.py:153} INFO - Started process (PID=3566) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:16:38.575-0400] {processor.py:743} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:16:38.576-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:16:38.575-0400] {dagbag.py:538} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:16:38.592-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:16:38.591-0400] {dagbag.py:343} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/drift-retrainer/venv311/lib/python3.11/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:16:38.592-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:16:39.215-0400] {processor.py:175} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 0.643 seconds
[2025-06-13T14:17:33.801-0400] {processor.py:153} INFO - Started process (PID=3998) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:17:33.803-0400] {processor.py:743} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:17:33.803-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:17:33.803-0400] {dagbag.py:538} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:17:33.817-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:17:33.816-0400] {dagbag.py:343} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/drift-retrainer/venv311/lib/python3.11/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:17:33.818-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:17:34.281-0400] {processor.py:175} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 0.481 seconds
[2025-06-13T14:18:32.990-0400] {processor.py:153} INFO - Started process (PID=6338) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:18:32.992-0400] {processor.py:743} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:18:32.992-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:18:32.992-0400] {dagbag.py:538} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:18:33.007-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:18:33.006-0400] {dagbag.py:343} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/drift-retrainer/venv311/lib/python3.11/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:18:33.007-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:18:33.478-0400] {processor.py:175} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 0.489 seconds
[2025-06-13T14:19:35.272-0400] {processor.py:153} INFO - Started process (PID=6515) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:19:35.274-0400] {processor.py:743} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:19:35.275-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:19:35.275-0400] {dagbag.py:538} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:19:35.289-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:19:35.288-0400] {dagbag.py:343} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/drift-retrainer/venv311/lib/python3.11/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:19:35.289-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:19:35.764-0400] {processor.py:175} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 0.493 seconds
[2025-06-13T14:20:38.730-0400] {processor.py:153} INFO - Started process (PID=6722) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:20:38.732-0400] {processor.py:743} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:20:38.732-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:20:38.732-0400] {dagbag.py:538} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:20:38.753-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:20:38.753-0400] {dagbag.py:343} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/drift-retrainer/venv311/lib/python3.11/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:20:38.753-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:20:39.257-0400] {processor.py:175} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 0.527 seconds
[2025-06-13T14:21:15.775-0400] {processor.py:186} INFO - Started process (PID=7322) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:21:15.777-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:21:15.778-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:21:15.778-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:21:15.791-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:21:15.789-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:21:15.792-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:21:16.121-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 347.531 seconds
[2025-06-13T14:23:23.091-0400] {processor.py:186} INFO - Started process (PID=7821) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:23:23.093-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:23:23.095-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:23:23.095-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:23:23.102-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:23:23.101-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:23:23.102-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:23:23.473-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 385.107 seconds
[2025-06-13T14:24:55.338-0400] {processor.py:186} INFO - Started process (PID=7949) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:24:55.341-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:24:55.341-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:24:55.341-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:24:55.346-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:24:55.345-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:24:55.346-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:24:55.725-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 387.864 seconds
[2025-06-13T14:26:26.623-0400] {processor.py:186} INFO - Started process (PID=8059) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:26:26.625-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:26:26.626-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:26:26.626-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:26:26.631-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:26:26.630-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:26:26.631-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:26:26.971-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 350.465 seconds
[2025-06-13T14:27:58.386-0400] {processor.py:186} INFO - Started process (PID=8757) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:27:58.388-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:27:58.389-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:27:58.389-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:27:58.396-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:27:58.395-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:27:58.396-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:27:58.820-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 435.932 seconds
[2025-06-13T14:29:30.287-0400] {processor.py:186} INFO - Started process (PID=8882) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:29:30.291-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:29:30.291-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:29:30.291-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:29:30.296-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:29:30.295-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:29:30.296-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:29:30.615-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 329.456 seconds
[2025-06-13T14:30:59.685-0400] {processor.py:186} INFO - Started process (PID=9320) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:30:59.688-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:30:59.688-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:30:59.688-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:30:59.693-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:30:59.692-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:30:59.693-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:31:00.074-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 390.665 seconds
[2025-06-13T14:32:27.954-0400] {processor.py:186} INFO - Started process (PID=9519) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:32:27.956-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:32:27.956-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:32:27.956-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:32:27.961-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:32:27.960-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:32:27.961-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:32:28.261-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 308.731 seconds
[2025-06-13T14:34:01.609-0400] {processor.py:186} INFO - Started process (PID=9782) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:34:01.612-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:34:01.613-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:34:01.613-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:34:01.618-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:34:01.617-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:34:01.618-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:34:02.008-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 400.340 seconds
[2025-06-13T14:35:33.267-0400] {processor.py:186} INFO - Started process (PID=10171) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:35:33.270-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:35:33.271-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:35:33.271-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:35:33.278-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:35:33.277-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:35:33.278-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:35:33.596-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 333.237 seconds
[2025-06-13T14:37:03.946-0400] {processor.py:186} INFO - Started process (PID=11019) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:37:03.948-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:37:03.950-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:37:03.950-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:37:03.957-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:37:03.954-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:37:03.957-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:37:04.379-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 435.216 seconds
[2025-06-13T14:38:33.104-0400] {processor.py:186} INFO - Started process (PID=11227) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:38:33.106-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:38:33.107-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:38:33.107-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:38:33.121-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:38:33.121-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:38:33.121-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:38:33.457-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 355.157 seconds
[2025-06-13T14:39:56.013-0400] {processor.py:186} INFO - Started process (PID=11453) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:39:56.015-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:39:56.015-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:39:56.015-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:39:56.018-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:39:56.018-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:39:56.018-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:39:56.275-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 263.146 seconds
[2025-06-13T14:41:13.609-0400] {processor.py:186} INFO - Started process (PID=11728) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:41:13.611-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:41:13.611-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:41:13.611-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:41:13.614-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:41:13.614-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:41:13.614-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:41:13.866-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 258.424 seconds
[2025-06-13T14:42:28.634-0400] {processor.py:186} INFO - Started process (PID=11837) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:42:28.635-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:42:28.636-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:42:28.636-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:42:28.638-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:42:28.638-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:42:28.639-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:42:28.908-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 275.704 seconds
[2025-06-13T14:43:41.565-0400] {processor.py:186} INFO - Started process (PID=11975) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:43:41.566-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:43:41.567-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:43:41.567-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:43:41.569-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:43:41.569-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:43:41.569-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:43:41.827-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 263.283 seconds
[2025-06-13T14:44:53.611-0400] {processor.py:186} INFO - Started process (PID=12124) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:44:53.613-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:44:53.613-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:44:53.613-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:44:53.616-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:44:53.616-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:44:53.616-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:44:53.879-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 269.076 seconds
[2025-06-13T14:46:06.356-0400] {processor.py:186} INFO - Started process (PID=12300) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:46:06.358-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:46:06.358-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:46:06.358-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:46:06.361-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:46:06.360-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:46:06.361-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:46:06.610-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 254.937 seconds
[2025-06-13T14:47:17.746-0400] {processor.py:186} INFO - Started process (PID=12391) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:47:17.748-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:47:17.748-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:47:17.748-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:47:17.751-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:47:17.750-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:47:17.751-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:47:18.003-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 258.123 seconds
[2025-06-13T14:48:33.898-0400] {processor.py:186} INFO - Started process (PID=12503) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:48:33.900-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:48:33.901-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:48:33.901-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:48:33.904-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:48:33.903-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:48:33.904-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:48:34.161-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 264.444 seconds
[2025-06-13T14:49:47.290-0400] {processor.py:186} INFO - Started process (PID=12624) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:49:47.293-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:49:47.293-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:49:47.293-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:49:47.297-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:49:47.296-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:49:47.297-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:49:47.557-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 268.069 seconds
[2025-06-13T14:51:01.643-0400] {processor.py:186} INFO - Started process (PID=12745) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:51:01.644-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:51:01.645-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:51:01.645-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:51:01.648-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:51:01.648-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:51:01.648-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:51:01.904-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 262.453 seconds
[2025-06-13T14:52:16.742-0400] {processor.py:186} INFO - Started process (PID=13993) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:52:16.744-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:52:16.744-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:52:16.744-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:52:16.748-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:52:16.748-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:52:16.748-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:52:17.068-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 327.957 seconds
[2025-06-13T14:53:30.719-0400] {processor.py:186} INFO - Started process (PID=14092) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:53:30.721-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:53:30.722-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:53:30.722-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:53:30.725-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:53:30.724-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:53:30.725-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:53:30.982-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 264.325 seconds
[2025-06-13T14:54:46.910-0400] {processor.py:186} INFO - Started process (PID=14206) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:54:46.913-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:54:46.913-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:54:46.913-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:54:46.917-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:54:46.916-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:54:46.917-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:54:47.181-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 272.119 seconds
[2025-06-13T14:56:05.476-0400] {processor.py:186} INFO - Started process (PID=14351) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:56:05.478-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:56:05.478-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:56:05.478-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:56:05.481-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:56:05.481-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:56:05.481-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:56:05.736-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 261.468 seconds
[2025-06-13T14:57:19.612-0400] {processor.py:186} INFO - Started process (PID=14450) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:57:19.614-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:57:19.615-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:57:19.615-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:57:19.618-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:57:19.618-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/retraining_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/retraining_dag.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:57:19.619-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:57:19.932-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 320.367 seconds
[2025-06-13T14:58:43.274-0400] {processor.py:186} INFO - Started process (PID=14698) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:58:43.276-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T14:58:43.277-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:43.277-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:58:43.283-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T14:58:43.710-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:43.710-0400] {override.py:1930} INFO - Created Permission View: can read on DAG:retrain_pipeline
[2025-06-13T14:58:43.713-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:43.713-0400] {override.py:1930} INFO - Created Permission View: can delete on DAG:retrain_pipeline
[2025-06-13T14:58:43.715-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:43.715-0400] {override.py:1930} INFO - Created Permission View: can edit on DAG:retrain_pipeline
[2025-06-13T14:58:43.719-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:43.718-0400] {override.py:1930} INFO - Created Permission View: menu access on DAG Run:retrain_pipeline
[2025-06-13T14:58:43.721-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:43.721-0400] {override.py:1930} INFO - Created Permission View: can read on DAG Run:retrain_pipeline
[2025-06-13T14:58:43.723-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:43.723-0400] {override.py:1930} INFO - Created Permission View: can create on DAG Run:retrain_pipeline
[2025-06-13T14:58:43.725-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:43.725-0400] {override.py:1930} INFO - Created Permission View: can delete on DAG Run:retrain_pipeline
[2025-06-13T14:58:43.725-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:43.725-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T14:58:43.729-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:43.729-0400] {dag.py:3262} INFO - Creating ORM DAG for retrain_pipeline
[2025-06-13T14:58:43.732-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:43.732-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T17:00:00+00:00, run_after=2025-06-13T18:00:00+00:00
[2025-06-13T14:58:43.739-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 465.930 seconds
[2025-06-13T15:00:04.621-0400] {processor.py:186} INFO - Started process (PID=14836) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:00:04.624-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:00:04.624-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:00:04.624-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:00:04.631-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:00:10.911-0400] {processor.py:186} INFO - Started process (PID=14923) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:00:10.913-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:00:10.913-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:00:10.913-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:00:10.920-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:00:11.203-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:00:11.203-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:00:11.211-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:00:11.211-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:00:11.257-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 347.874 seconds
[2025-06-13T15:02:10.131-0400] {processor.py:186} INFO - Started process (PID=15240) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:02:10.133-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:02:10.134-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:02:10.134-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:02:10.141-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:02:10.700-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:02:10.700-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:02:10.709-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:02:10.708-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:02:10.758-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 628.360 seconds
[2025-06-13T15:03:47.269-0400] {processor.py:186} INFO - Started process (PID=15730) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:03:47.271-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:03:47.272-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:03:47.271-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:03:47.277-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:03:47.719-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:03:47.719-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:03:47.729-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:03:47.729-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:03:47.787-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 519.930 seconds
[2025-06-13T15:04:14.780-0400] {processor.py:186} INFO - Started process (PID=15887) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:04:14.782-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:04:14.783-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:04:14.783-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:04:14.788-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:04:15.064-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:04:15.063-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:04:15.071-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:04:15.071-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:04:15.117-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 338.037 seconds
[2025-06-13T15:06:12.459-0400] {processor.py:186} INFO - Started process (PID=16273) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:06:12.461-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:06:12.462-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:06:12.462-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:06:12.467-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:06:12.963-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:06:12.963-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:06:12.971-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:06:12.971-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:06:13.020-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 561.875 seconds
[2025-06-13T15:07:32.939-0400] {processor.py:186} INFO - Started process (PID=16424) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:07:32.942-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:07:32.942-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:07:32.942-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:07:32.948-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:07:33.231-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:07:33.230-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:07:33.238-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:07:33.238-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:07:33.282-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 343.689 seconds
[2025-06-13T15:08:51.216-0400] {processor.py:186} INFO - Started process (PID=16518) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:08:51.218-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:08:51.218-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:08:51.218-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:08:51.224-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:08:51.674-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:08:51.674-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:08:51.681-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:08:51.681-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:08:51.731-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 516.002 seconds
[2025-06-13T15:10:14.917-0400] {processor.py:186} INFO - Started process (PID=16755) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:10:14.919-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:10:14.919-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:10:14.919-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:10:14.925-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:10:15.204-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:10:15.203-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:10:15.211-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:10:15.211-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:10:15.255-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 338.936 seconds
[2025-06-13T15:11:42.355-0400] {processor.py:186} INFO - Started process (PID=16880) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:11:42.357-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:11:42.358-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:11:42.358-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:11:42.364-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:11:42.887-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:11:42.887-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:11:42.896-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:11:42.895-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:11:42.944-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 590.074 seconds
[2025-06-13T15:13:07.239-0400] {processor.py:186} INFO - Started process (PID=17048) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:13:07.241-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:13:07.242-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:13:07.242-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:13:07.248-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:13:07.732-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:13:07.732-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:13:07.740-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:13:07.740-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:13:07.790-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 552.802 seconds
[2025-06-13T15:18:27.283-0400] {processor.py:186} INFO - Started process (PID=17682) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:18:27.285-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:18:27.286-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:18:27.286-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:18:27.291-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:18:27.631-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:18:27.631-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:18:27.638-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:18:27.638-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:18:27.646-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 364.562 seconds
[2025-06-13T15:20:23.307-0400] {processor.py:186} INFO - Started process (PID=17883) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:20:23.309-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:20:23.310-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:20:23.309-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:20:23.315-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:20:23.767-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:20:23.767-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:20:23.775-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:20:23.775-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:20:23.826-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 520.074 seconds
[2025-06-13T15:24:33.665-0400] {processor.py:186} INFO - Started process (PID=18775) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:24:33.668-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:24:33.668-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:24:33.668-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:24:33.675-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:24:34.179-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:24:34.179-0400] {override.py:1930} INFO - Created Permission View: can edit on DAG:retrain_pipeline
[2025-06-13T15:24:34.183-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:24:34.183-0400] {override.py:1930} INFO - Created Permission View: can read on DAG:retrain_pipeline
[2025-06-13T15:24:34.185-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:24:34.185-0400] {override.py:1930} INFO - Created Permission View: can delete on DAG:retrain_pipeline
[2025-06-13T15:24:34.188-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:24:34.188-0400] {override.py:1930} INFO - Created Permission View: can create on DAG Run:retrain_pipeline
[2025-06-13T15:24:34.191-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:24:34.191-0400] {override.py:1930} INFO - Created Permission View: can read on DAG Run:retrain_pipeline
[2025-06-13T15:24:34.193-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:24:34.193-0400] {override.py:1930} INFO - Created Permission View: menu access on DAG Run:retrain_pipeline
[2025-06-13T15:24:34.195-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:24:34.195-0400] {override.py:1930} INFO - Created Permission View: can delete on DAG Run:retrain_pipeline
[2025-06-13T15:24:34.196-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:24:34.195-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:24:34.200-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:24:34.200-0400] {dag.py:3262} INFO - Creating ORM DAG for retrain_pipeline
[2025-06-13T15:24:34.204-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:24:34.204-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:24:34.211-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 546.543 seconds
[2025-06-13T15:26:43.342-0400] {processor.py:186} INFO - Started process (PID=19048) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:26:43.344-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:26:43.346-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:26:43.345-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:26:43.355-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:26:43.943-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:26:43.943-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:26:43.951-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:26:43.951-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:26:44.013-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 673.079 seconds
[2025-06-13T15:27:26.085-0400] {processor.py:186} INFO - Started process (PID=19306) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:27:26.087-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:27:26.088-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:27:26.088-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:27:26.093-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:27:26.517-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:27:26.516-0400] {override.py:1930} INFO - Created Permission View: can read on DAG:retrain_pipeline
[2025-06-13T15:27:26.521-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:27:26.521-0400] {override.py:1930} INFO - Created Permission View: can delete on DAG:retrain_pipeline
[2025-06-13T15:27:26.524-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:27:26.524-0400] {override.py:1930} INFO - Created Permission View: can edit on DAG:retrain_pipeline
[2025-06-13T15:27:26.527-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:27:26.527-0400] {override.py:1930} INFO - Created Permission View: can read on DAG Run:retrain_pipeline
[2025-06-13T15:27:26.529-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:27:26.529-0400] {override.py:1930} INFO - Created Permission View: can delete on DAG Run:retrain_pipeline
[2025-06-13T15:27:26.532-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:27:26.531-0400] {override.py:1930} INFO - Created Permission View: menu access on DAG Run:retrain_pipeline
[2025-06-13T15:27:26.534-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:27:26.534-0400] {override.py:1930} INFO - Created Permission View: can create on DAG Run:retrain_pipeline
[2025-06-13T15:27:26.534-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:27:26.534-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:27:26.539-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:27:26.538-0400] {dag.py:3262} INFO - Creating ORM DAG for retrain_pipeline
[2025-06-13T15:27:26.542-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:27:26.542-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:27:26.549-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 464.826 seconds
[2025-06-13T15:28:47.762-0400] {processor.py:186} INFO - Started process (PID=19637) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:28:47.764-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:28:47.765-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:28:47.765-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:28:47.770-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:28:48.129-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:28:48.129-0400] {override.py:1930} INFO - Created Permission View: can delete on DAG:retrain_pipeline
[2025-06-13T15:28:48.133-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:28:48.133-0400] {override.py:1930} INFO - Created Permission View: can read on DAG:retrain_pipeline
[2025-06-13T15:28:48.135-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:28:48.135-0400] {override.py:1930} INFO - Created Permission View: can edit on DAG:retrain_pipeline
[2025-06-13T15:28:48.138-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:28:48.138-0400] {override.py:1930} INFO - Created Permission View: can delete on DAG Run:retrain_pipeline
[2025-06-13T15:28:48.143-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:28:48.143-0400] {override.py:1930} INFO - Created Permission View: can read on DAG Run:retrain_pipeline
[2025-06-13T15:28:48.145-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:28:48.145-0400] {override.py:1930} INFO - Created Permission View: menu access on DAG Run:retrain_pipeline
[2025-06-13T15:28:48.147-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:28:48.147-0400] {override.py:1930} INFO - Created Permission View: can create on DAG Run:retrain_pipeline
[2025-06-13T15:28:48.148-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:28:48.147-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:28:48.152-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:28:48.152-0400] {dag.py:3262} INFO - Creating ORM DAG for retrain_pipeline
[2025-06-13T15:28:48.156-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:28:48.156-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:28:48.161-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 400.161 seconds
[2025-06-13T15:29:56.954-0400] {processor.py:186} INFO - Started process (PID=19769) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:29:56.956-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:29:56.956-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:29:56.956-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:29:56.964-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:29:57.373-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:29:57.373-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:29:57.383-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:29:57.383-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:29:57.437-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 484.462 seconds
[2025-06-13T15:32:00.021-0400] {processor.py:186} INFO - Started process (PID=19989) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:32:00.022-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:32:00.023-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:32:00.023-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:32:00.028-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:32:00.522-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:32:00.522-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:32:00.529-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:32:00.529-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:32:00.576-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 556.781 seconds
[2025-06-13T15:35:28.676-0400] {processor.py:186} INFO - Started process (PID=20342) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:35:28.678-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:35:28.679-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:35:28.679-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:35:28.685-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:35:29.035-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:35:29.035-0400] {override.py:1930} INFO - Created Permission View: can edit on DAG:retrain_pipeline
[2025-06-13T15:35:29.039-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:35:29.039-0400] {override.py:1930} INFO - Created Permission View: can read on DAG:retrain_pipeline
[2025-06-13T15:35:29.041-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:35:29.041-0400] {override.py:1930} INFO - Created Permission View: can delete on DAG:retrain_pipeline
[2025-06-13T15:35:29.044-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:35:29.044-0400] {override.py:1930} INFO - Created Permission View: menu access on DAG Run:retrain_pipeline
[2025-06-13T15:35:29.046-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:35:29.046-0400] {override.py:1930} INFO - Created Permission View: can read on DAG Run:retrain_pipeline
[2025-06-13T15:35:29.048-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:35:29.048-0400] {override.py:1930} INFO - Created Permission View: can delete on DAG Run:retrain_pipeline
[2025-06-13T15:35:29.050-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:35:29.050-0400] {override.py:1930} INFO - Created Permission View: can create on DAG Run:retrain_pipeline
[2025-06-13T15:35:29.050-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:35:29.050-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:35:29.055-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:35:29.055-0400] {dag.py:3262} INFO - Creating ORM DAG for retrain_pipeline
[2025-06-13T15:35:29.058-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:35:29.058-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:35:29.064-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 389.424 seconds
[2025-06-13T15:37:33.136-0400] {processor.py:186} INFO - Started process (PID=20675) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:37:33.138-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:37:33.138-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:37:33.138-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:37:33.145-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:37:33.535-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:37:33.535-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:37:33.543-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:37:33.543-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:37:33.592-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 457.847 seconds
[2025-06-13T15:38:56.987-0400] {processor.py:186} INFO - Started process (PID=20799) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:38:56.990-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:38:56.990-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:38:56.990-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:38:56.996-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:38:57.352-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:38:57.352-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:38:57.360-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:38:57.360-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:38:57.415-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 428.312 seconds
[2025-06-13T15:40:21.803-0400] {processor.py:186} INFO - Started process (PID=20927) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:40:21.805-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:40:21.806-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:40:21.806-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:40:21.812-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:40:22.287-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:40:22.287-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:40:22.295-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:40:22.295-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:40:22.341-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 538.928 seconds
[2025-06-13T15:41:50.537-0400] {processor.py:186} INFO - Started process (PID=21074) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:41:50.539-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:41:50.539-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:41:50.539-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:41:50.545-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:41:50.992-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:41:50.992-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:41:51.001-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:41:51.001-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:41:51.049-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 514.132 seconds
[2025-06-13T15:42:59.163-0400] {processor.py:186} INFO - Started process (PID=21395) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:42:59.165-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:42:59.166-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:42:59.166-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:42:59.173-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:42:59.554-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:42:59.554-0400] {override.py:1930} INFO - Created Permission View: can delete on DAG:retrain_pipeline
[2025-06-13T15:42:59.558-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:42:59.558-0400] {override.py:1930} INFO - Created Permission View: can edit on DAG:retrain_pipeline
[2025-06-13T15:42:59.563-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:42:59.563-0400] {override.py:1930} INFO - Created Permission View: can read on DAG:retrain_pipeline
[2025-06-13T15:42:59.567-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:42:59.567-0400] {override.py:1930} INFO - Created Permission View: can delete on DAG Run:retrain_pipeline
[2025-06-13T15:42:59.569-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:42:59.569-0400] {override.py:1930} INFO - Created Permission View: can create on DAG Run:retrain_pipeline
[2025-06-13T15:42:59.571-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:42:59.571-0400] {override.py:1930} INFO - Created Permission View: menu access on DAG Run:retrain_pipeline
[2025-06-13T15:42:59.574-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:42:59.574-0400] {override.py:1930} INFO - Created Permission View: can read on DAG Run:retrain_pipeline
[2025-06-13T15:42:59.574-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:42:59.574-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:42:59.579-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:42:59.579-0400] {dag.py:3262} INFO - Creating ORM DAG for retrain_pipeline
[2025-06-13T15:42:59.583-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:42:59.583-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:42:59.590-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 427.875 seconds
[2025-06-13T15:45:05.344-0400] {processor.py:186} INFO - Started process (PID=21827) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:45:05.346-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:45:05.347-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:45:05.347-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:45:05.352-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:45:05.947-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:45:05.946-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:45:05.955-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:45:05.955-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:45:06.004-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 660.778 seconds
[2025-06-13T15:46:35.049-0400] {processor.py:186} INFO - Started process (PID=22009) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:46:35.051-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:46:35.052-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:46:35.052-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:46:35.060-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:46:35.478-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:46:35.478-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:46:35.486-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:46:35.485-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:46:35.532-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 486.313 seconds
[2025-06-13T15:48:01.494-0400] {processor.py:186} INFO - Started process (PID=22117) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:48:01.496-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:48:01.497-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:48:01.497-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:48:01.503-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:48:02.054-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:48:02.054-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:48:02.064-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:48:02.064-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:48:02.121-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 629.034 seconds
[2025-06-13T15:49:25.568-0400] {processor.py:186} INFO - Started process (PID=22258) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:49:25.570-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:49:25.571-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:49:25.571-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:49:25.577-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:49:25.985-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:49:25.985-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:49:25.993-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:49:25.993-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:49:26.041-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 474.062 seconds
[2025-06-13T15:50:49.882-0400] {processor.py:186} INFO - Started process (PID=22392) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:50:49.884-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:50:49.884-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:50:49.884-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:50:49.890-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:50:50.348-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:50:50.347-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:50:50.355-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:50:50.355-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:50:50.404-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 522.899 seconds
[2025-06-13T15:52:02.155-0400] {processor.py:186} INFO - Started process (PID=22603) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:52:02.157-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:52:02.158-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:52:02.157-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:52:02.163-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:52:02.418-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:52:02.418-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:52:02.425-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:52:02.425-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:52:02.467-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 312.989 seconds
[2025-06-13T15:53:17.329-0400] {processor.py:186} INFO - Started process (PID=22722) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:53:17.330-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:53:17.331-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:53:17.331-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:53:17.335-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:53:17.592-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:53:17.592-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:53:17.599-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:53:17.599-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:53:17.641-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 314.002 seconds
[2025-06-13T15:54:31.134-0400] {processor.py:186} INFO - Started process (PID=22867) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:54:31.136-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:54:31.136-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:54:31.136-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:54:31.141-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:54:31.394-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:54:31.394-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:54:31.402-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:54:31.402-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:54:31.443-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 310.547 seconds
[2025-06-13T15:55:42.654-0400] {processor.py:186} INFO - Started process (PID=22957) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:55:42.656-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:55:42.656-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:55:42.656-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:55:42.661-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:55:42.980-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:55:42.980-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:55:42.988-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:55:42.988-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:55:43.030-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 377.082 seconds
[2025-06-13T15:56:55.715-0400] {processor.py:186} INFO - Started process (PID=23060) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:56:55.717-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:56:55.717-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:56:55.717-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:56:55.722-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:56:55.987-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:56:55.987-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:56:55.995-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:56:55.995-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:56:56.038-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 324.843 seconds
[2025-06-13T15:58:06.791-0400] {processor.py:186} INFO - Started process (PID=23190) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:58:06.793-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:58:06.793-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:58:06.793-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:58:06.800-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:58:07.170-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:58:07.170-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:58:07.178-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:58:07.178-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:58:07.221-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 431.248 seconds
[2025-06-13T15:59:19.298-0400] {processor.py:186} INFO - Started process (PID=23392) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:59:19.300-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T15:59:19.300-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:59:19.300-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:59:19.305-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T15:59:19.583-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:59:19.583-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T15:59:19.590-0400] {logging_mixin.py:190} INFO - [2025-06-13T15:59:19.590-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T18:00:00+00:00, run_after=2025-06-13T19:00:00+00:00
[2025-06-13T15:59:19.634-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 337.354 seconds
[2025-06-13T16:00:33.130-0400] {processor.py:186} INFO - Started process (PID=23584) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T16:00:33.133-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T16:00:33.133-0400] {logging_mixin.py:190} INFO - [2025-06-13T16:00:33.133-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T16:00:33.139-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T16:00:33.462-0400] {logging_mixin.py:190} INFO - [2025-06-13T16:00:33.462-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T16:00:33.470-0400] {logging_mixin.py:190} INFO - [2025-06-13T16:00:33.470-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T19:00:00+00:00, run_after=2025-06-13T20:00:00+00:00
[2025-06-13T16:00:33.513-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 384.426 seconds
[2025-06-13T16:01:49.388-0400] {processor.py:186} INFO - Started process (PID=23797) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T16:01:49.390-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T16:01:49.390-0400] {logging_mixin.py:190} INFO - [2025-06-13T16:01:49.390-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T16:01:49.396-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T16:01:49.709-0400] {logging_mixin.py:190} INFO - [2025-06-13T16:01:49.708-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T16:01:49.716-0400] {logging_mixin.py:190} INFO - [2025-06-13T16:01:49.716-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T19:00:00+00:00, run_after=2025-06-13T20:00:00+00:00
[2025-06-13T16:01:49.758-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 371.491 seconds
[2025-06-13T16:03:08.974-0400] {processor.py:186} INFO - Started process (PID=23989) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T16:03:08.976-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T16:03:08.976-0400] {logging_mixin.py:190} INFO - [2025-06-13T16:03:08.976-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T16:03:08.982-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T16:03:09.470-0400] {logging_mixin.py:190} INFO - [2025-06-13T16:03:09.470-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T16:03:09.478-0400] {logging_mixin.py:190} INFO - [2025-06-13T16:03:09.478-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T19:00:00+00:00, run_after=2025-06-13T20:00:00+00:00
[2025-06-13T16:03:09.533-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 560.692 seconds
[2025-06-13T16:08:09.271-0400] {processor.py:186} INFO - Started process (PID=24241) to work on /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T16:08:09.273-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/retraining_dag.py for tasks to queue
[2025-06-13T16:08:09.274-0400] {logging_mixin.py:190} INFO - [2025-06-13T16:08:09.274-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T16:08:09.281-0400] {processor.py:925} INFO - DAG(s) 'retrain_pipeline' retrieved from /Users/pranavr/drift-retrainer/dags/retraining_dag.py
[2025-06-13T16:08:09.767-0400] {logging_mixin.py:190} INFO - [2025-06-13T16:08:09.767-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T16:08:09.775-0400] {logging_mixin.py:190} INFO - [2025-06-13T16:08:09.775-0400] {dag.py:4180} INFO - Setting next_dagrun for retrain_pipeline to 2025-06-13T19:00:00+00:00, run_after=2025-06-13T20:00:00+00:00
[2025-06-13T16:08:09.828-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/retraining_dag.py took 558.047 seconds
